version: 0.1.0.{build}

image: Visual Studio 2019

build_script:
  - echo "This step would build the artifacts"

artifacts:
  - path: build-output/unsigned/combined.zip

environment:
  SIGNPATH_SIGNING_POLICY_SLUG: test-signing
  ARTIFACT_CONFIGURATION_SLUG: v1
for:
  -
    branches:
      only:
        - /release/.*/
        - master
    environment:
      SIGNPATH_SIGNING_POLICY_SLUG: release-signing

deploy:
  - provider: Webhook
    url: https://app.signpath.io/API/v1/%SIGNPATH_ORGANIZATION_ID%/Integrations/AppVeyor?ProjectSlug=%SIGNPATH_PROJECT_SLUG%&SigningPolicySlug=%SIGNPATH_SIGNING_POLICY_SLUG%&ArtifactConfigurationSlug=%ARTIFACT_CONFIGURATION_SLUG%
    authorization: 'Bearer %SIGNPATH_CI_USER_TOKEN%'

